import React,{useEffect,useMemo,useState}from'react';import{createRoot}from'react-dom/client';import OBSWebSocket from'obs-websocket-js';import'./index.css';
type Task={id:string;text:string;done:boolean};type Plan={title:string;subtitle:string;visible:boolean;tasks:Task[]};type Saved={address:string;password:string;micInput:string;musicInput:string;plan:Plan;questionableDecisions:number};
const KEY='silverbullet-stream-control';const defaults:Saved={address:'ws://192.168.1.2:4455',password:'',micInput:'Mic/Aux',musicInput:'Media',plan:{title:'Stream Plan',subtitle:"Tonight's increasingly questionable decisions.",visible:false,tasks:[]},questionableDecisions:0};
const load=():Saved=>{try{return{...defaults,...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return defaults}};const save=(s:Saved)=>localStorage.setItem(KEY,JSON.stringify(s));
const obs=new OBSWebSocket();
function App(){const[s,setS]=useState<Saved>(load),[connected,setConnected]=useState(false),[error,setError]=useState(''),[scenes,setScenes]=useState<string[]>([]),[program,setProgram]=useState(''),[preview,setPreview]=useState(''),[studio,setStudio]=useState(false),[inputs,setInputs]=useState<string[]>([]);
const patch=(n:Saved)=>{setS(n);save(n)};const refresh=async()=>{if(!connected)return;try{const[sl,sm,il]=await Promise.all([obs.call('GetSceneList'),obs.call('GetStudioModeEnabled'),obs.call('GetInputList')]);setScenes(sl.scenes.map((x:any)=>x.sceneName));setProgram(sl.currentProgramSceneName);setPreview(sl.currentPreviewSceneName||'');setStudio(sm.studioModeEnabled);setInputs(il.inputs.map((x:any)=>x.inputName));}catch(e:any){setError(e.message||String(e))}};
const connect=async()=>{setError('');try{await obs.connect(s.address,s.password,{rpcVersion:1});setConnected(true);await refresh()}catch(e:any){setConnected(false);setError(e.message||String(e))}};const disconnect=async()=>{try{await obs.disconnect()}finally{setConnected(false)}};
useEffect(()=>{const timer=setInterval(refresh,1500);return()=>clearInterval(timer)},[connected]);useEffect(()=>{const onClose=()=>setConnected(false);obs.on('ConnectionClosed',onClose);return()=>{obs.off('ConnectionClosed',onClose)}},[]);
const act=async(type:string,data:any={})=>{try{if(type==='preview')await obs.call('SetCurrentPreviewScene',{sceneName:data.scene});if(type==='transition')await obs.call('TriggerStudioModeTransition');if(type==='studio')await obs.call('SetStudioModeEnabled',{studioModeEnabled:!studio});if(type==='mute')await obs.call('ToggleInputMute',{inputName:data.name});await refresh()}catch(e:any){setError(e.message||String(e))}};
const p=s.plan;return <main className="mx-auto max-w-xl p-4 pb-12 space-y-4"><header><h1 className="text-2xl font-black">Silverbullet Stream Control</h1><p className="text-zinc-400 text-sm">v0.2 · browser → OBS directly</p></header>
<section className="rounded-2xl border border-zinc-800 bg-zinc-900 p-4"><div className="flex justify-between items-center"><b>Connection</b><span className={connected?'text-emerald-400':'text-red-400'}>{connected?'CONNECTED':'OFFLINE'}</span></div><label className="block text-xs text-zinc-400 mt-3">OBS WebSocket address</label><input value={s.address} onChange={e=>patch({...s,address:e.target.value})} placeholder="ws://192.168.1.123:4455" className="mt-1 w-full rounded-lg bg-zinc-950 border border-zinc-700 p-3"/><label className="block text-xs text-zinc-400 mt-3">Password</label><input type="password" value={s.password} onChange={e=>patch({...s,password:e.target.value})} className="mt-1 w-full rounded-lg bg-zinc-950 border border-zinc-700 p-3"/><button onClick={connected?disconnect:connect} className="mt-3 w-full min-h-14 rounded-xl bg-white text-black font-black">{connected?'DISCONNECT':'CONNECT TO OBS'}</button>{error&&<p className="mt-3 text-sm text-red-400">{error}</p>}<p className="mt-2 text-xs text-zinc-500">Connection details stay in this browser's local storage.</p></section>
<section className="rounded-2xl border border-zinc-800 bg-zinc-900 p-4"><div className="text-sm text-zinc-400">PROGRAM <b className="text-white">{program||'—'}</b><br/>PREVIEW <b className="text-white">{preview||'—'}</b></div><div className="grid grid-cols-2 gap-2 mt-3">{scenes.map(x=><button key={x} disabled={!connected} onClick={()=>act('preview',{scene:x})} className={'min-h-14 rounded-xl border px-3 font-bold '+(preview===x?'border-white bg-zinc-700':'border-zinc-700 bg-zinc-800')}>{x}</button>)}</div><button disabled={!connected} onClick={()=>act('transition')} className="mt-3 w-full min-h-16 rounded-xl bg-white text-black text-lg font-black disabled:opacity-40">TRANSITION →</button></section>
<section className="rounded-2xl border border-zinc-800 bg-zinc-900 p-4"><b>Quick Controls</b><div className="grid grid-cols-2 gap-2 mt-3"><button onClick={()=>patch({...s,plan:{...p,visible:!p.visible}})} className="min-h-14 rounded-xl bg-zinc-800 font-bold">{p.visible?'Hide':'Show'} Stream Plan</button><button disabled={!connected} onClick={()=>act('mute',{name:s.micInput})} className="min-h-14 rounded-xl bg-zinc-800 font-bold disabled:opacity-40">Toggle Mic</button><button disabled={!connected} onClick={()=>act('mute',{name:s.musicInput})} className="min-h-14 rounded-xl bg-zinc-800 font-bold disabled:opacity-40">Toggle Music</button><button disabled={!connected} onClick={()=>act('studio')} className="min-h-14 rounded-xl bg-zinc-800 font-bold disabled:opacity-40">Studio {studio?'ON':'OFF'}</button></div><label className="block text-xs text-zinc-400 mt-3">Mic input</label><select value={s.micInput} onChange={e=>patch({...s,micInput:e.target.value})} className="mt-1 w-full rounded-lg bg-zinc-950 border border-zinc-700 p-3">{Array.from(new Set([s.micInput,...inputs])).map(x=><option key={x}>{x}</option>)}</select><label className="block text-xs text-zinc-400 mt-3">Music input</label><select value={s.musicInput} onChange={e=>patch({...s,musicInput:e.target.value})} className="mt-1 w-full rounded-lg bg-zinc-950 border border-zinc-700 p-3">{Array.from(new Set([s.musicInput,...inputs])).map(x=><option key={x}>{x}</option>)}</select></section>
<section className="rounded-2xl border border-zinc-800 bg-zinc-900 p-4"><div className="flex justify-between"><b>Stream Plan</b><button onClick={()=>patch({...s,plan:{...p,tasks:[...p.tasks,{id:crypto.randomUUID(),text:'New objective',done:false}]}})} className="rounded-lg bg-zinc-800 px-3">+ Task</button></div><input value={p.title} onChange={e=>patch({...s,plan:{...p,title:e.target.value}})} className="mt-3 w-full rounded-lg bg-zinc-950 border border-zinc-700 p-3"/><input value={p.subtitle} onChange={e=>patch({...s,plan:{...p,subtitle:e.target.value}})} className="mt-2 w-full rounded-lg bg-zinc-950 border border-zinc-700 p-3"/><div className="mt-3 space-y-2">{p.tasks.map((t,i)=><div key={t.id} className="flex gap-2"><input type="checkbox" checked={t.done} onChange={e=>{const a=[...p.tasks];a[i]={...t,done:e.target.checked};patch({...s,plan:{...p,tasks:a}})}}/><input value={t.text} onChange={e=>{const a=[...p.tasks];a[i]={...t,text:e.target.value};patch({...s,plan:{...p,tasks:a}})}} className="min-w-0 flex-1 rounded-lg bg-zinc-950 border border-zinc-700 p-3"/><button onClick={()=>patch({...s,plan:{...p,tasks:p.tasks.filter(y=>y.id!==t.id)}})} className="px-3 rounded-lg bg-zinc-800">×</button></div>)}</div></section>
<section className="rounded-2xl border border-zinc-800 bg-zinc-900 p-4"><b>Questionable Decisions</b><div className="flex items-center gap-3 mt-3"><button onClick={()=>patch({...s,questionableDecisions:Math.max(0,s.questionableDecisions-1)})} className="h-14 w-14 rounded-xl bg-zinc-800 text-xl">−</button><div className="flex-1 text-center text-4xl font-black">{s.questionableDecisions}</div><button onClick={()=>patch({...s,questionableDecisions:s.questionableDecisions+1})} className="h-14 w-14 rounded-xl bg-white text-black text-xl">+</button></div><button onClick={()=>patch({...s,questionableDecisions:s.questionableDecisions+1})} className="mt-3 w-full min-h-14 rounded-xl bg-zinc-800 font-black">I HAVE MADE A MISTAKE</button></section></main>}
createRoot(document.getElementById('root')!).render(<App/>);